site_name: GDPR
repo_url: https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.magiclink
pages:
- Introduction: index.md
- Overview: Overview.md
- Installation: Installation.md
- Identifying Inactive Contacts: Identifying Inactive Contacts.md
- Communication Preferences: Communication Preferences.md
- Data Policy: Data Policy.md
- Membership Terms and Conditions: Membership Terms and Conditions.md
- Events Terms and Conditions: Events Terms and Conditions.md


