site_name: GDPR
repo_url: https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.magiclink
pages:
- Introduction: index.md

