site_name: GDPR
repo_url: https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.magiclink
pages:
1. Introduction: index.md
*  What is GDPR
*  Why this extension is needed
1. Overview
*  What does the extension introduce
1. Installation
*  New permissions introduced
*  General Settings
*  Comms Prefs settings
1. Identifying Inactive Contacts
*  How to
*  What can you do with them
1. Communication Preferences
1. Data Policy
1. Membership Terms and Conditions
1. Events Terms and Conditions


